# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-29 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180525_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='inventory.OrderItems'),
        ),
    ]
