# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180529_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'C:\\Users\\nakamura9a\\Documents\\code\\git\\scms\\media'),
        ),
    ]
