# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180608_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='received_items',
            field=models.ManyToManyField(to='inventory.OrderItems'),
        ),
    ]
