# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180612_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='maximum_stock_level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_order_level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
