# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Burser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('billing_address', models.CharField(max_length=128, null=True)),
                ('phone_two', models.CharField(max_length=16, null=True)),
                ('account_number', models.CharField(max_length=16, null=True)),
                ('other_details', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('date', models.DateField()),
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('terms', models.CharField(max_length=64)),
                ('comments', models.TextField(null=True)),
                ('paid_in_full', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Account')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('item_name', models.CharField(max_length=32)),
                ('unit_price', models.FloatField()),
                ('description', models.CharField(max_length=128)),
                ('code', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('debit card', 'Debit Card'), ('ecocash', 'EcoCash')], max_length=32)),
                ('reference_number', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Account')),
                ('burser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Burser')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.InvoiceItem'),
        ),
        migrations.AddField(
            model_name='account',
            name='bursers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Burser'),
        ),
    ]
