# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20180514_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceItem',
            new_name='Item',
        ),
    ]
