# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20180515_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Burser',
            new_name='SalesRep',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='bursers',
            new_name='reps',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='burser',
            new_name='sales_rep',
        ),
    ]
