# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_auto_20180515_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Payment',
        ),
    ]
