# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_auto_20180515_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='title',
            field=models.CharField(choices=[('teller', 'Teller'), ('admin', 'Administrator')], default='teller', max_length=32),
            preserve_default=False,
        ),
    ]
