# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_salesrep_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.InvoiceItem'),
        ),
    ]
