# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_auto_20180517_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.InvoiceItem'),
        ),
    ]
