# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_auto_20180517_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(null=True, to='invoicing.InvoiceItem'),
        ),
    ]
