# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_auto_20180517_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice'),
        ),
    ]
