# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_auto_20180521_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(to='invoicing.InvoiceItem'),
        ),
    ]
