# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180608_0911'),
        ('invoicing', '0014_auto_20180608_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('date', models.DateField(default=datetime.date.today)),
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='items',
            field=models.ManyToManyField(to='invoicing.QuoteItem'),
        ),
    ]
