# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_auto_20180611_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
