# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20180609_2231'),
        ('invoicing', '0017_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.SalesRep'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Tax'),
        ),
        migrations.AddField(
            model_name='quote',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.SalesRep'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Tax'),
        ),
    ]
