# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0018_auto_20180611_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
