# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_auto_20180612_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
