# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ledger',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Journal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.TextField(default='transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
