# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180608_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustmet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='WorkBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='adjustmet',
            name='workbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.WorkBook'),
        ),
    ]
